---
- name: "pull monasca {{image}} | Pull image"
  become: true
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ service.image }}"

# image: "{{ service.image }}"
